name: Debug

on:
  workflow_dispatch:

jobs:
  Build-PC:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]

    steps:
    - name: Obtain latest version of the repository
      uses: actions/checkout@v4
    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install requirements with PIP
      run: pip install --break-system-packages -r requirements.txt
    - name: Install pyinstaller
      run: pip install --break-system-packages pyinstaller
    - name: Build RiiTag RPC
      run: pyinstaller riitag-rpc.spec
    - name: Mark as executable
      if: ${{ matrix.os != 'windows-2022' }}
      run: chmod -R +x dist/
    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-x64
        path: dist

  Collect-Artifacts:
    runs-on: ubuntu-22.04
    needs: [Build-PC]
    steps:
      - name: Download windows-2022-x64
        uses: actions/download-artifact@v4
        with:
          name: windows-2022-x64
          path: windows

      - name: Get environment variables
        id: get_repository_name
        run: |
          echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV
          echo DATETIME=$(echo $(date '+%Y%m%d-%H%M%S')) >> $GITHUB_ENV
      
      - name: Collect artifacts
        run: |
          mkdir -p releases
          mv  windows/riitag-rpc.exe releases/RiiTag-RPC_Windows.exe
          chmod -R +x releases/
          tar -cvf all-artifacts.tar.bz2 releases/

      - name: Publish collected artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-artifacts
          path: all-artifacts.tar.bz2
